Sprint 2 Carl Tomo
JiecongYANG/voc pull request #6
Opened 2021-09-20 15:40 UTC by carlenlund

2021-09-21 13:18 UTC, carlenlund commented
> In my view, the code is good but since it seems bulky it should be nice if you include some comments to make it simple understandable to some extent.

Thanks for the feedback! I've added explanatory comments in c644d96

2021-09-22 10:07 UTC, ralfkatt requested changes
No duplication of code.
Code is located in the correct files and directories.
Coding conventions seems to be followed.
Code appears maintainable, follows the single responsibility principle.
All tests pass.
Tests coverage is good for methods (95%)  and lines (97%).

TODOS

- [ ] Look over the naming of "test_timedelta" that is python naming convention but Java should be used so: "testTimeDelta
- [ ] Also the name of the tests follow: "test_TimeDelta_kwargs" which should be "testTimeDeltaKwargs.

2021-09-22 10:17 UTC, carlenlund commented
> No duplication of code.
> Code is located in the correct files and directories.
> Coding conventions seems to be followed.
> Code appears maintainable, follows the single responsibility principle.
> All tests pass.
> Tests coverage is good for methods (95%) and lines (97%).
> 
> TODOS
> 
> * [ ]  Look over the naming of "test_timedelta" that is python naming convention but Java should be used so: "testTimeDelta
> * [ ]  Also the name of the tests follow: "test_TimeDelta_kwargs" which should be "testTimeDeltaKwargs.

Thanks, fixed in 15328fe

2021-09-22 11:06 UTC, ralfkatt approved these changes

2021-09-22 13:21 UTC, merged